#!/usr/bin/env node
/* ─────────────────────────────────────────
   build-pages.mjs — gives every project a real URL

   Run from the site folder after editing index.html or content.js:

       node tools/build-pages.mjs

   What it writes (all generated, never edit these by hand):

     projects/<slug>/index.html   one per entry in PROJECTS. A copy of
                                  index.html with the project's own title,
                                  description and link-preview image, so a
                                  shared link unfurls as that case study on
                                  LinkedIn, iMessage, Slack, etc.
     404.html                     GitHub Pages serves this for unknown paths.
                                  If someone opens projects/<slug>/ for a
                                  project that hasn't been built yet, it
                                  forwards them to the #/project/<slug>
                                  route, so the link still works.
     sitemap.xml                  lists the homepage and every project page.
                                  (A robots.txt would have to live at the
                                  domain root, not under /portfolio/, so to
                                  point Google at this, submit it once in
                                  Google Search Console.)

   Link-preview images are read from static/og/og-<slug>.jpg (1200x630).
   A project without one falls back to static/og/og-home.jpg.

   No dependencies: plain Node 18+.
───────────────────────────────────────── */

import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const rel = p => path.join(ROOT, p);
const MARK = '<!-- GENERATED by tools/build-pages.mjs from index.html + static/content.js. Do not edit; edit those and re-run. -->';

/* ── Load content.js the same way the browser does ── */
const ctx = {};
vm.createContext(ctx);
vm.runInContext(
  fs.readFileSync(rel('static/content.js'), 'utf8') + '\n;this.__out = { SITE, PROJECTS };',
  ctx
);
const { SITE, PROJECTS } = ctx.__out;
const SITE_URL = (SITE.url || '').replace(/\/?$/, '/');
if (!/^https?:\/\//.test(SITE_URL)) {
  console.error('SITE.url in static/content.js must be the full address of the live site.');
  process.exit(1);
}

const esc = s => String(s)
  .replace(/&/g, '&amp;').replace(/"/g, '&quot;')
  .replace(/</g, '&lt;').replace(/>/g, '&gt;');
const clean = s => String(s || '').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();

const template = fs.readFileSync(rel('index.html'), 'utf8');
const META_RE = /<!-- META:START -->[\s\S]*?<!-- META:END -->/;
const BASE_RE = /<!-- BASE[^>]*-->/;
if (!META_RE.test(template) || !BASE_RE.test(template)) {
  console.error('index.html is missing the <!-- BASE --> or <!-- META:START/END --> markers.');
  process.exit(1);
}

function metaFor(slug, p) {
  const url   = `${SITE_URL}projects/${encodeURIComponent(slug)}/`;
  const ogRel = fs.existsSync(rel(`static/og/og-${slug}.jpg`)) ? `static/og/og-${slug}.jpg` : 'static/og/og-home.jpg';
  const img   = SITE_URL + ogRel;
  const title = `${clean(p.title)} — ${SITE.name}`;
  const ogTitle = `${clean(p.title)}: ${clean(p.sub)}`;
  const desc  = clean(p.summary || p.cardDesc);
  return `<!-- META:START -->
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(desc)}">
  <link rel="canonical" href="${esc(url)}">
  <meta property="og:site_name" content="${esc(SITE.name)}">
  <meta property="og:title" content="${esc(ogTitle)}">
  <meta property="og:description" content="${esc(desc)}">
  <meta property="og:image" content="${esc(img)}">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="${esc(ogTitle)}">
  <meta property="og:url" content="${esc(url)}">
  <meta property="og:type" content="article">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${esc(ogTitle)}">
  <meta name="twitter:description" content="${esc(desc)}">
  <meta name="twitter:image" content="${esc(img)}">
  <!-- META:END -->`;
}

/* ── projects/<slug>/index.html ── */
const slugs = Object.keys(PROJECTS);
fs.mkdirSync(rel('projects'), { recursive: true });

for (const slug of slugs) {
  const html = template
    .replace('<html lang="en">', `<html lang="en" data-project="${esc(slug)}">`)
    .replace(BASE_RE, `${MARK}\n  <base href="../../">`)
    .replace(META_RE, () => metaFor(slug, PROJECTS[slug]));
  const dir = rel(`projects/${slug}`);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'index.html'), html);
  console.log(`  projects/${slug}/`);
}

/* Remove pages for projects that no longer exist, but only folders this
   script created (identified by the GENERATED marker). */
for (const name of fs.readdirSync(rel('projects'))) {
  if (slugs.includes(name)) continue;
  const f = rel(`projects/${name}/index.html`);
  if (fs.existsSync(f) && fs.readFileSync(f, 'utf8').includes(MARK)) {
    fs.rmSync(rel(`projects/${name}`), { recursive: true });
    console.log(`  removed stale projects/${name}/`);
  }
}

/* ── 404.html ── */
fs.writeFileSync(rel('404.html'), `<!DOCTYPE html>
${MARK}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="robots" content="noindex">
  <title>Page not found — ${esc(SITE.name)}</title>
  <script>
    /* A project page that hasn't been generated yet: forward to the
       in-page route for it, which always works. */
    (function () {
      var m = location.pathname.match(/^(.*\\/)projects\\/([^/]+)\\/?(?:index\\.html)?$/);
      if (m) location.replace(m[1] + '#/project/' + m[2]);
    })();
  </script>
  <style>
    html, body { margin: 0; height: 100%; background: #0b0b0b; color: #f0ede8;
                 font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
    main { min-height: 100%; display: flex; flex-direction: column; justify-content: center;
           padding: 0 1.5rem; max-width: 40rem; margin: 0 auto; box-sizing: border-box; }
    h1 { font-family: Georgia, serif; font-weight: 400; font-size: 2.5rem; margin: 0 0 1rem; }
    p { color: #a3a3a3; line-height: 1.7; margin: 0 0 1.5rem; }
    a { color: #2fa876; }
  </style>
</head>
<body>
  <main>
    <h1>Page not found</h1>
    <p>That link doesn't go anywhere on this site.</p>
    <p><a href="${esc(SITE_URL)}">Go to ${esc(SITE.name)}'s portfolio</a></p>
  </main>
</body>
</html>
`);
console.log('  404.html');

/* ── sitemap.xml ── */
const today = new Date().toISOString().slice(0, 10);
const urls = [SITE_URL, ...slugs.map(s => `${SITE_URL}projects/${encodeURIComponent(s)}/`)];
fs.writeFileSync(rel('sitemap.xml'),
`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url><loc>${esc(u)}</loc><lastmod>${today}</lastmod></url>`).join('\n')}
</urlset>
`);
console.log('  sitemap.xml');

console.log(`\nBuilt ${slugs.length} project pages.`);
